### ISSUE TITLE
Terraform Provider Review

### ISSUE THREAD

**Issue by mbfrahry** [rightscale/terraform-provider-rightscale#70]
Hello! My name is Matthew Frahry and I'm part of the Terraform Ecosystem Team. I've started going through this provider and I have to say that it looks great! I'm a fan of the 1-1 mapping of the naming between Terraform attributes and api Field attributes. I have some minor comments about documentation, questions about the implementation, and some further considerations/improvements for the provider. You understand this provider and api better than I do so please take this with a grain of salt and let me know if I'm off base with any of my notes. 

- [x] There is some language in the docs we can clean up that is already a given for Terraform like,  `Registration of clouds in a given RightScale account will need to have been executed ahead of time to define it as a cloud datasource.` From this [file](https://github.com/rightscale/terraform-provider-rightscale/blob/master/website/docs/d/cm_cloud.markdown)
This is how datasources work and shouldn’t need to be specified.

- [x] We try to maintain consistency with the other provider docs and one thing I noticed that could potentially be jarring when moving from doc to doc is `REQUIRED` and `OPTIONAL` and we should swap those to `Required` and `Optional`. This is very minor but helps make the website look cleaner

- [x] Additional context is preferred when talking about the nuances of a resource but we should clean up the language [here](https://github.com/rightscale/terraform-provider-rightscale/blob/master/website/docs/d/cm_image.markdown). 
`Beware that searching a very popular cloud (say aws us-east) based on name with 'visibility = "public"' is gonna be slow…`

 - [x] The ordering of the attributes is a little off [here](https://github.com/rightscale/terraform-provider-rightscale/blob/master/website/docs/r/cm_server.markdown)
We should group all the required attributes together and then follow with the Optional attributes. This is so that a user knows exactly what attributes to pass to get up and running without having to look through all the documentation. 

- [x] There is a some inconsistency with datasource tests. It looks like all the datasources are being tested but you have datasource test files and datasource tests in resource tests. This is fine but we might want to try and make it consistent with either having every datasource with it's own test file. 

- [x] There are a couple of places in the docs that note cloud_specific_attributes but not what exactly you can pass into it. We should add those fields into the docs. Noticed [here](https://github.com/rightscale/terraform-provider-rightscale/blob/9aa19fea1d7ad929b2f14a956438744764bd65c8/website/docs/d/cm_instance.markdown) and [here](https://github.com/rightscale/terraform-provider-rightscale/blob/9aa19fea1d7ad929b2f14a956438744764bd65c8/website/docs/r/cm_instance.markdown)

- [x] It’s best practice to only set the id in the create method and then set all the other attributes in the corresponding read function. Is there a reason you’re setting the attributes in the create method?

The following aren't action items but more food for thought that I'd like to discuss.

- [x] I don’t know a ton about api development at RightScale but I do see a potential issue with how you pass and receive attributes. It looks like an almost one to one mapping of terraform attribute to Field name (minus one or two that you take care of).It’s interesting seeing how you can shorten code because the attribute names in the terraform config match almost exactly with the api field names. My only concern is if ever the api changes the field names, terraform breaks and this can cause issues with subsequent terraform runs. This works for now but in case you aren’t in charge of the api,  issues may come from when those names change in the api. 

- [x] Another potential note is that you use TypeList is everywhere and we’ve seen issues come in where the api returns an unordered list back and that can cause issues where you pass a list of 1,2,3 and the api returns 2,3,1. Terraform will try and fix this when it doesn’t need fixing. In that case you should use TypeSet but if your api returns the list back the same way you sent it than you’re good! No action items here but just noting something that bites a lot of  providers. 

- [x] I don’t see importable resources anywhere in the provider and that’s fine to not have them but they are very helpful to people who already have resources set up and would like to manage those with Terraform. It’s fairly easy to get added to a resource if that was something you were interested in adding.

**Comment by mastamark** [comment]
Excellent, thank you @mbfrahry!  I'll be breaking these into some stories to get done and flesh out responses to your questions about the API in the next few days.

Is there any hard blockers you see at all in your review, or can I assume that once we clean up the docs a a bit and otherwise address your questions its smooth sailing into acceptance-ville?

**Comment by mbfrahry** [comment]
Hey @mastamark the above sounds good! I did just find a hard blocker in that your [client.go](https://github.com/rightscale/terraform-provider-rightscale/blob/master/rightscale/rsc/client.go) because it has panics in it. This could cause some horrendous issues in Terraform , for example, a user could be running your provider and another provider at the same time. The other provider is in the midst of creating resources and then your provider panics, those resources on that cloud aren't kept track in Terraform anymore and the user will have to manually deal with them which isn't ideal. Panics are also an easy way to lose a statefile and so we try extremely hard to steer away from them when we can. Is there any chance you can just return an error in that file instead of panicing?

**Comment by mastamark** [comment]
I have a few tickets breaking up the asks from above around docs cleanup, the datasource tests, and of course removing the hard blocker of the panics.  Should have that all pushed up to master by next week sometime.

To answer your questions:
* "... My only concern is if ever the api changes the field names, terraform breaks and this can cause issues with subsequent terraform runs. This works for now but in case you aren’t in charge of the api, issues may come from when those names change in the api."
=> RS is a cloud infrastructure company who have been around for a pretty long time - and have customers who have been with us for a long time.  Since those customers use us to build their own critical infrastructure, we can't easily change the api on folks without extensive communication out to customers.  Basically we end up rolling versioned apis and continue to support previous versions, so we I can promise that our names will not change.

* Our use of TypeList everywhere - same thing applies as above.  Once we publish an API if we muck with the ordering then it breaks customer automation so we can confirm that will stay the same.  (But that's a good pro tip for the future!)

* Importable resources: So this one was a conscious effort on my part to sidestep adding that for the initial review/addition as a supported provider.  I do hope to start adding those in down the line, but I was channeling the guide you guys publish that suggested not going all out initially before we got to this review.  (I assume just in case we released some truly terrible code and then had tons of refactoring work)

**Comment by mbfrahry** [comment]
Thanks for taking the time to answer my questions. Your answers make total sense and it's good to see your committed to not breaking your api for users. Luckily for the importable resources you didn't write terrible code so it should be fairly painless to add that support once we release! 

I'll keep an eye out for PRs related to this review and let you know if I see anything odd

**Comment by crunis** [comment]
Hi @mbfrahry ,

We have just merged #71 that removed all the usages of `panic` in the code and #72 that addressed your suggestions on documentation.

The only thing that remains addressing is your comment: 

> There is a some inconsistency with datasource tests. It looks like all the datasources are being tested but you have datasource test files and datasource tests in resource tests. This is fine but we might want to try and make it consistent with either having every datasource with it's own test file.

We have been testing together resource and datasource because that allows us to create the resource and then retrieve it with the datasource, otherwise we need to have preexisting resources in our account to tests the datasources, and that far from ideal.
But then there are many objects like "volume_type", "cloud", "datacenter",... that get created during account setup (when you link RightScale to your cloud accounts) and have no Terraform resource, and yet, the datasource is still very useful to retrieve the IDs of these resources. In this cases we only have defined the datasource in Terraform and they have their own test file.

That is why we have the current list of test files. Still, if we want it to be more uniform, we could just rename the "resource_xxxx_test" files (that contain both resource and datasource) to "datasource_xxxx_test", since most of the defined resources have a datasource counterpart, that would result in a more uniform list of tests. How does it sound to you ?

**Comment by mastamark** [comment]
We have addressed all issues//questions from the above issue @mbfrahry except for the tests which @crunis is seeking feedback from you on.  :1st_place_medal:

**Comment by mbfrahry** [comment]
Hey @crunis, for #71, the changes there are a little confusing. In some [places](https://github.com/rightscale/terraform-provider-rightscale/pull/71/files#diff-36a0b64dbf028ec2d07dff980cb5c1f3R979) You're now returning an empty string for all the the panics but it seems like we'd be losing information on why we errored. What're your thoughts on returning an error like `fmt.Errorf("encountered an error with req: %+v", err`. Unless this is a deliberate change then disregard the above comment.

There are also two more panics in [client_test](https://github.com/rightscale/terraform-provider-rightscale/blob/9aa19fea1d7ad929b2f14a956438744764bd65c8/rightscale/rsc/client_test.go)

So for testing datasources, you can also take take the config from the resource tests and append the datasource config but yes, you're recreating the same resource again. We like to split it out but the way you have it makes sense and we can keep it that way.

**Comment by crunis** [comment]
Hi @mbfrahry,

The code that had the panics retrieves the username and email of the user that is executing Terraform (these fields are retrieved from his RightScale account). The username is displayed in the logs of our systems when they execute the actions of the Terraform plan.
Your comment about the panics made me realise that it was silly to interrupt the flow of terraform if, for some reason, the username or email can't be retrieved. Now that code just returns "" in case of error and that gets translated into "Terraform user" in our platform logs.
What I could do is add a warning in the logs if we hit some of the previous panic conditions, so the attentive user can see them and try to fix them, how does it sound to you ?

The panics you point out are inside the tests, they should never happen unless someone messes up while adding more tests. Still I can try to change the panic for something like "t.Fatal" but I'm not  sure that's going to work well because the error condition happens inside the mock HTTP server used during the tests.

I'd like to avoid creating again resources in the datasource tests because the tests take already quite a bit to execute and that would increase that time.

**Comment by mbfrahry** [comment]
That all makes sense to me! I think we are good from a review stand point. Thanks for taking the time to address my concerns!
